// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvMfAKrGbmoPrhKdaYDRYzwWGrmNSimuc',
    appId: '1:752105909467:web:8b43d03e17741ef480b0fe',
    messagingSenderId: '752105909467',
    projectId: 'mandir-griha',
    authDomain: 'mandir-griha.firebaseapp.com',
    storageBucket: 'mandir-griha.firebasestorage.app',
    measurementId: 'G-2806GDC406',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAekUkHXFcs-2SO0WW2EPOScQC7dDli5vY',
    appId: '1:752105909467:android:3fc5c9936f2f015980b0fe',
    messagingSenderId: '752105909467',
    projectId: 'mandir-griha',
    storageBucket: 'mandir-griha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM34IjKrtgve-P4UGsmxAEu_t2b6-9DgA',
    appId: '1:752105909467:ios:2000a48e055c28c980b0fe',
    messagingSenderId: '752105909467',
    projectId: 'mandir-griha',
    storageBucket: 'mandir-griha.firebasestorage.app',
    iosBundleId: 'com.example.poojaPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM34IjKrtgve-P4UGsmxAEu_t2b6-9DgA',
    appId: '1:752105909467:ios:2000a48e055c28c980b0fe',
    messagingSenderId: '752105909467',
    projectId: 'mandir-griha',
    storageBucket: 'mandir-griha.firebasestorage.app',
    iosBundleId: 'com.example.poojaPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvMfAKrGbmoPrhKdaYDRYzwWGrmNSimuc',
    appId: '1:752105909467:web:3fa5d7495ed8ee6a80b0fe',
    messagingSenderId: '752105909467',
    projectId: 'mandir-griha',
    authDomain: 'mandir-griha.firebaseapp.com',
    storageBucket: 'mandir-griha.firebasestorage.app',
    measurementId: 'G-EJN38TLB7S',
  );
}
